### ISSUE TITLE
Custom xml(gml) file 

### ISSUE THREAD

**Issue by RamanaBotta** [Fields2Cover/fields2cover_ros#10]
Hi Team,
I am unable to load custom GML(XML) files, to the fields2cover_ros package.
and can you guys share how to create a custom XML file,  which tool to use, and any shape specifications etc.

The GML file I have used is attached below and that did not work.

[qgis.zip](https://github.com/Fields2Cover/fields2cover_ros/files/10378898/qgis.zip)

**Comment by Gonzalo-Mier** [comment]
GML importer is quite tailor-made... So I doubt it can load your file. You can read the code [here](https://github.com/Fields2Cover/Fields2Cover/blob/eabc182286311e5fa3bc6c053c020d0e0774cfb0/src/fields2cover/utils/parser.cpp#L17)

The GML we use comes from a previous project I haven't participated, so not sure how they made it. You can use as a template the files on the data folder

**Comment by RamanaBotta** [comment]
Yes, I am using the GML template.
Thank you.
