### ISSUE TITLE
Error when doing catkin_make_isolated in ros noetic

### ISSUE THREAD

**Issue by Botronics** [Fields2Cover/fields2cover_ros#11]
I am using Ros Noetic. i followed  all the procedures given in github and documentation. But still I'm facing issue when I'm doing catkin_make_isolated. i am unable to run it in my lap. i installed all the dependencies given and still its not running. if there is any way to solve this kindly please help me out.
```
Make Error at /home/boson/autopilot_ws/src/autopilot_boson/build_isolated/fields2cover/devel/Fields2CoverConfig.cmake:6 (include):
  include could not find load file:

    /home/boson/autopilot_ws/src/autopilot_boson/devel_isolated/fields2cover/cmake/fields2cover/Fields2CoverTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:27 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/boson/field_ws/build_isolated/fields2cover_ros/CMakeFiles/CMakeOutput.log".
See also "/home/boson/field_ws/build_isolated/fields2cover_ros/CMakeFiles/CMakeError.log".
<== Failed to process package 'fields2cover_ros': 
  Command '['/home/boson/field_ws/devel_isolated/fields2cover/env.sh', 'cmake', '/home/boson/field_ws/src/fields2cover_ros', '-DCATKIN_DEVEL_PREFIX=/home/boson/field_ws/devel_isolated/fields2cover_ros', '-DCMAKE_INSTALL_PREFIX=/home/boson/field_ws/install_isolated', '-G', 'Unix Makefiles']' returned non-zero exit status 1.

Reproduce this error by running:
==> cd /home/boson/field_ws/build_isolated/fields2cover_ros && /home/boson/field_ws/devel_isolated/fields2cover/env.sh cmake /home/boson/field_ws/src/fields2cover_ros -DCATKIN_DEVEL_PREFIX=/home/boson/field_ws/devel_isolated/fields2cover_ros -DCMAKE_INSTALL_PREFIX=/home/boson/field_ws/install_isolated -G 'Unix Makefiles'

Command failed, exiting.
```

**Comment by Gonzalo-Mier** [comment]
Hi @Botronics,
Thanks for the issue. I'll work on this soon.

Please, avoid contact me by email if you already have written an issue about it. I solve issues whenever I can, as I'm not earning any money to maintain this repository and I do it on my free time (Right now, I'm the only one maintaining this repo). If you believe this deserve more energy, please, try to solve it and submit a PR.
Best,
Gonzalo

**Comment by Gonzalo-Mier** [comment]
Solved on [the last commit of Fields2Cover](https://github.com/Fields2Cover/Fields2Cover/commit/411d9dd5579fa3031b8cb73d20b1512398e581dd)
