### ISSUE TITLE
How to save the produced path points into a json file. 

### ISSUE THREAD

**Issue by RamanaBotta** [Fields2Cover/fields2cover_ros#15]
Hi @Gonzalo-Mier,
I would like to save the generated path points into a Geojson file,
Can you please direct me on, how to do it?

**Comment by Gonzalo-Mier** [comment]
Hi @RamanaBotta,
Could you please open the same issue on the main Fields2Cover repo? It's better to maintain the repos organised in case others search for the same info.

**Comment by RamanaBotta** [comment]
Sure @Gonzalo-Mier

**Comment by RamanaBotta** [comment]
Created new issue: https://github.com/Fields2Cover/Fields2Cover/issues/57

closing it.
