### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by 9lovewh** [Fields2Cover/fields2cover_ros#16]
When I compiled the project using Ubuntu 18.04, ROS multimedia, the following error was reported:
CMake Error at /opt/cmake-3.25.3/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find GDAL: Found unsuitable version "2.4.2", but required is at
least "3.0" (found /usr/lib/libgdal.so)
May I ask how to solve it? Thank you.

**Comment by Gonzalo-Mier** [comment]
Hi @9lovewh and welcome. This error is because of the GDAL version installed. Have you follow the installation process? Make sure the GDAL version is higher than 3.0.0

**Comment by 9lovewh** [comment]
Thank you for your answer. My GDAL version is 2.4, but when I use sudo apt-get remove/install libgdal dev, I will remove many&nbsp; packages from the ros-melodic. The prompt is as follows:
The following software packages are automatically installed and are no longer needed:
cython evemu-tools evtest fltk1.3-doc fluid gazebo9-common joystick
libarmadillo-dev libarmadillo8 libarpack2 libarpack2-dev libavdevice-dev
libavdevice57 libavfilter-dev libcharls-dev libdap-dev libdapserver7v5
libepsilon-dev libevemu3 libfltk-cairo1.3 libfltk-forms1.3 libfltk-gl1.3
libfltk-images1.3 libfltk1.3 libfltk1.3-dev libfluidsynth1 libfreeimage-dev
libfreexl-dev libfyba-dev libgeos-dev libgeotiff-dev libgif-dev libgl2ps-dev
libgts-dev libhdf5-mpi-dev libhdf5-openmpi-dev libignition-cmake-dev
libignition-common libignition-common-dev libignition-fuel-tools1-1
libignition-fuel-tools1-dev libignition-math4-dev libignition-msgs-dev
libignition-transport4 libignition-transport4-dev libjson-c-dev
libjsoncpp-dev libkml-dev libkmlconvenience1 libkmlregionator1 libkmlxsd1
libmad0 libmikmod3 libminizip-dev libnetcdf-cxx-legacy-dev libogdi-dev
libogg-dev libopenal-data libopenal1 libopenjp2-7-dev libopenni2-dev
libpcl-apps1.8 libpoppler-dev libpoppler-private-dev libportmidi0
libpostproc-dev libproj-dev libqt5designercomponents5 libqt5quickparticles5
libqt5quicktest5 libqt5quickwidgets5 libqt5webkit5-dev libqwt-headers
libqwt-qt5-6 libqwt-qt5-dev libsdformat6 libsdformat6-dev libsdl-mixer1.2
libsdl-ttf2.0-0 libsdl2-2.0-0 libsimbody-dev libsimbody3.5v5 libsmpeg0
libspatialite-dev libsuperlu-dev libsuperlu5 libtar-dev libtar0
libtheora-dev liburiparser-dev libusb-0.1-4 libusb-dev libvtk6-java
libvtk6-jni libxerces-c-dev libxmu-dev libxmu-headers libxss-dev libyaml-dev
libzip-dev libzip4 libzmq3-dev libzstd-dev python-autobahn python-bluez
python-cbor python-h5py python-lz4 python-mpi4py python-nacl python-pygame
python-pyudev python-qrcode python-sklearn python-sklearn-lib python-snappy
python-trie python-trollius python-txaio python-u-msgpack python-ubjson
python-vtk6 python-wsaccel qt5-assistant qtdeclarative5-dev qttools5-dev
qttools5-dev-tools qttools5-private-dev ros-melodic-audio-video-recorder
ros-melodic-camera-calibration ros-melodic-checkerboard-detector
ros-melodic-compressed-depth-image-transport
ros-melodic-diff-drive-controller ros-melodic-eus-nlopt ros-melodic-eus-qp
ros-melodic-eus-qpoases ros-melodic-gazebo-msgs ros-melodic-image-common
ros-melodic-image-pipeline ros-melodic-image-publisher
ros-melodic-image-rotate ros-melodic-image-transport-plugins
ros-melodic-image-view ros-melodic-joy ros-melodic-joy-mouse
ros-melodic-laser-pipeline ros-melodic-multi-map-server
ros-melodic-octomap-ros ros-melodic-opencv-apps ros-melodic-openni2-camera
ros-melodic-openni2-launch ros-melodic-people-msgs ros-melodic-polled-camera
ros-melodic-position-controllers ros-melodic-ps3joy
ros-melodic-resized-image-transport ros-melodic-stage ros-melodic-stage-ros
ros-melodic-stereo-image-proc ros-melodic-theora-image-transport
ros-melodic-view-controller-msgs ros-melodic-virtual-force-publisher
ros-melodic-vision-opencv sdformat-sdf tcl-dev tcl-vtk6 tcl8.6-dev
timgm6mb-soundfont tk-dev tk8.6-dev ttf-dejavu-core vtk6
x11proto-scrnsaver-dev
Use 'sudo apt autoremove' to uninstall it (them).



吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 下午3:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
Hi @9lovewh and welcome. This error is because of the GDAL version installed. Have you follow the installation process? Make sure the GDAL version is higher than 3.0.0

**Comment by 9lovewh** [comment]
When I used cmake3.25 version, it reported that the gdal version was too low, but when I used cmake3.12 version, it reported an error and couldn't find tinyxml2 and GTest. The relevant prompt is as follows. Looking forward to your reply, thank you.


CMake Error at CMakeLists.txt:212 (install):
&nbsp; install TARGETS given target "tinyxml2" which does not exist in this
&nbsp; directory.


CMake Error at CMakeLists.txt:263 (export):
&nbsp; export given target "tinyxml2" which is not built by this project.


CMake Error at /opt/cmake-3.12.2/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
&nbsp; Could NOT find GTest (missing: GTEST_LIBRARY GTEST_MAIN_LIBRARY)








吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 下午3:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
Hi @9lovewh and welcome. This error is because of the GDAL version installed. Have you follow the installation process? Make sure the GDAL version is higher than 3.0.0

**Comment by Gonzalo-Mier** [comment]
You don't have to uninstall GDAL, but upgrade its version. Moreover the tinixml error is quite weird because that library is downloaded from internet during compilation. Which is your system?

**Comment by 9lovewh** [comment]
Thank you for your answer. My system is based on Ubuntu 18.04 and X86 architecture. Tinyxml2 error only occurs during cmake3.12 compilation.



吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
You don't have to uninstall GDAL, but upgrade its version. Moreover the tinixml error is quite weird because that library is downloaded from internet during compilation. Which is your system?

**Comment by 9lovewh** [comment]
Should I compile the readme installation dependencies in fields2cover first, and then compile the relevant feature packages for ROS？Looking forward to your reply. Thank you very much.



吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
You don't have to uninstall GDAL, but upgrade its version. Moreover the tinixml error is quite weird because that library is downloaded from internet during compilation. Which is your system?

**Comment by Gonzalo-Mier** [comment]
Yes, the errors come from the Fields2cover package (not the Ros one). Follow those installation instructions :)

**Comment by 9lovewh** [comment]
Okay, I will try upgrading the GDAL library again. If successful, I will write a&nbsp; document and upload it for everyone's reference. Thank you again.


吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
Yes, the errors come from the Fields2cover package (not the Ros one). Follow those installation instructions :)

**Comment by 9lovewh** [comment]
I'm sorry, I have another question to ask you. I have upgraded GDAL to 3.4.2. And I checked the version of gdal using gdalinfo version and gdal config version, and obtained the following results:GDAL 3.4.2, released 2022/03/08
3.4.2


But when I used cmake to compile fields2cover, the same error occurred:


CMake Error at /opt/cmake-3.25.3/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find GDAL: Found unsuitable version "2.4.2", but required is at
least "3.0" (found /usr/local/lib/libgdal.a)
Call Stack (most recent call first):
/opt/cmake-3.25.3/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
/opt/cmake-3.25.3/share/cmake-3.25/Modules/FindGDAL.cmake:185 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
/opt/cmake-3.25.3/share/cmake-3.25/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
/home/autowareapp/fields2cover_ ws/build_ isolated/fields2cover/devel/Fields2CoverConfig.cmake:4 (find_dependency)
fields2cover_ ros/CMakeLists.txt:13 (find_package)

吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
Yes, the errors come from the Fields2cover package (not the Ros one). Follow those installation instructions :)

**Comment by Gonzalo-Mier** [comment]
Not sure how to solve this actually. Seems that both gdal are living in your computer.

**Comment by 9lovewh** [comment]
I have successfully resolved the gdal version issue, but a new issue has arisen during compilation. Could you please answer it when you have time? Thank you.
The problem is as follows:
error: ‘class OGRSpatialReference’ has no member named ‘SetAxisMappingStrategy’



吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 中午1:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
Not sure how to solve this actually. Seems that both gdal are living in your computer.

**Comment by Gonzalo-Mier** [comment]
This error is due to using GDAL 2.  The function SetAxisMappingStrategy was added in GDAL 3.0, so unfortunately you are still linking against GDAL 2.something

**Comment by 9lovewh** [comment]
Okay, thank you for your answers. I resolved the issue with GDAL by uninstalling GDAL2.4.2, but when compiling fields2cover_ros, a new issue appeared. The problem is as follows:


/home/autowareapp/fields2cover_ws/src/fields2cover_ros/test/test_ros_conversor.cpp:49:25: error: expected constructor, destructor, or type conversion before ‘(’ token
&nbsp;INSTANTIATE_TEST_SUITE_P(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ^
/home/autowareapp/fields2cover_ws/src/fields2cover_ros/test/test_ros_conversor.cpp:53:57: error: expected unqualified-id before ‘,’ token
&nbsp;&nbsp;&nbsp;&nbsp; std::tuple<float_t, float_t, float_t&gt;{0.0, 0.0, 0.0},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ^
/home/autowareapp/fields2cover_ws/src/fields2cover_ros/test/test_ros_conversor.cpp:54:42: error: invalid declarator before ‘{’ token
&nbsp;&nbsp;&nbsp;&nbsp; std::tuple<float_t, float_t, float_t&gt;{1.2, 3.456, -7.9},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ^
/home/autowareapp/fields2cover_ws/src/fields2cover_ros/test/test_ros_conversor.cpp:54:60: error: expected unqualified-id before ‘,’ token
&nbsp;&nbsp;&nbsp;&nbsp; std::tuple<float_t, float_t, float_t&gt;{1.2, 3.456, -7.9},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ^
/home/autowareapp/fields2cover_ws/src/fields2cover_ros/test/test_ros_conversor.cpp:55:42: error: invalid declarator before ‘{’ token
&nbsp;&nbsp;&nbsp;&nbsp; std::tuple<float_t, float_t, float_t&gt;{20001.2787878, -3.456, -0.0}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ^
/home/autowareapp/fields2cover_ws/src/fields2cover_ros/test/test_ros_conversor.cpp:56:3: error: expected unqualified-id before ‘)’ token
&nbsp;&nbsp; )



吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 晚上6:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
This error is due to using GDAL 2.  The function SetAxisMappingStrategy was added in GDAL 3.0, so unfortunately you are still linking against GDAL 2.something

**Comment by 9lovewh** [comment]
When I set INSTANTATE_ TEST_ SUITE_ P () commented out, compiled successfully. Is this function necessary?



吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 晚上6:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
This error is due to using GDAL 2.  The function SetAxisMappingStrategy was added in GDAL 3.0, so unfortunately you are still linking against GDAL 2.something

**Comment by Gonzalo-Mier** [comment]
That's my fault. You can remove it for now. I'm on holidays until Tuesday. I'll solve it then. Thanks for reporting the errors

**Comment by 9lovewh** [comment]
Okay, thank you for your answer. I just have a new question. When I use 'roslauch fields2cover_ros view_field.launch', the following error occurs.


[ERROR] [1681003472.402555401]: PluginlibFactory: The plugin for class 'rviz_plugins/AerialMapDisplay' failed to load.&nbsp; Error: According to the loaded plugin descriptions the class rviz_plugins/AerialMapDisplay with base class type rviz::Display does not exist. Declared types are&nbsp; NavGridOfChars NavGridOfDoubles OccupancyGrid Path2D Polygon2D Polygon3D Polygons grid_map_rviz_plugin/GridMap moveit_rviz_plugin/MotionPlanning moveit_rviz_plugin/PlanningScene moveit_rviz_plugin/RobotState moveit_rviz_plugin/Trajectory robot_nav_rviz_plugins::SpectrumDisplay rviz/Axes rviz/Camera rviz/DepthCloud rviz/Effort rviz/FluidPressure rviz/Grid rviz/GridCells rviz/Illuminance rviz/Image rviz/InteractiveMarkers rviz/LaserScan rviz/Map rviz/Marker rviz/MarkerArray rviz/Odometry rviz/Path rviz/PointCloud rviz/PointCloud2 rviz/PointStamped rviz/Polygon rviz/Pose rviz/PoseArray rviz/PoseWithCovariance rviz/Range rviz/RelativeHumidity rviz/RobotModel rviz/TF rviz/Temperature rviz/WrenchStamped rviz_plugin_tutorials/Imu




吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月8日(星期六) 晚上11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
That's my fault. You can remove it for now. I'm on holidays until Tuesday. I'll solve it then. Thanks for reporting the errors

**Comment by 9lovewh** [comment]
Thank you for your answer. I have now successfully run through fields2cover_ ros, I found that example1.xml defines the size of the field. But there are still some questions I would like to consult with you. The first is that the field has only four vertices, why do you use 12 latitude and longitude coordinates to define it? The second issue is that the six edges in example1.xml seem to be ineffective, and isn't the field a quadrilateral? Why do we define six edges. Looking forward to your reply, thank you very much.




吴江东
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月8日(星期六) 晚上11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
That's my fault. You can remove it for now. I'm on holidays until Tuesday. I'll solve it then. Thanks for reporting the errors

**Comment by 9lovewh** [comment]
How can I replace the latitude and longitude in example1.xml with the latitude and longitude I need, EPSG:4258 is a set of coordinate systems used in Europe, and EPSG:28992 is a coordinate system exclusive to the Netherlands, do I need to modify both?




吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月8日(星期六) 晚上11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
That's my fault. You can remove it for now. I'm on holidays until Tuesday. I'll solve it then. Thanks for reporting the errors

**Comment by Gonzalo-Mier** [comment]
Hi @9lovewh,

Right now I'm not using the Edges represented in that file. Only the field geometry. The field is not a quadrilateral. It's a real field measured by my professor, and some sides are not completely straight. That's why there are more than 4 points there.

About the coordinate system, the field was measured using EPSG:4258. If your file is measured in other coordinate system, modify it accordingly. Inside the program, the first thing we do is transforming EPSG:4258 (long, lat) to a coordinate system that works in meters, preferably less than 1 meter error. For the example case, that was  EPSG:28992. Change it by the coordinate system that works better for your field (in meters).

**Comment by 9lovewh** [comment]
Thank you very much for your answer, as you said you need to convert latitude and longitude to meters. EPSG: 28992 is the Dutch latitude and longitude to meter standard, how do I find the Chinese latitude and longitude to meter standard, look forward to your answer, thank you very much.




吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
Hi @9lovewh,
 
Right now I'm not using the Edges represented in that file. Only the field geometry. The field is not a quadrilateral. It's a real field measured by my professor, and some sides are not completely straight. That's why there are more than 4 points there.
 
About the coordinate system, the field was measured using EPSG:4258. If your file is measured in other coordinate system, modify it accordingly. Inside the program, the first thing we do is transforming EPSG:4258 (long, lat) to a coordinate system that works in meters, preferably less than 1 meter error. For the example case, that was  EPSG:28992. Change it by the coordinate system that works better for your field (in meters).

**Comment by Gonzalo-Mier** [comment]
https://epsg.io/?q=china

Btw:
- EPSG:28992 is Dutch coordinate system in meters
- EPSG:4258 is Europe Long Lat.

**Comment by 9lovewh** [comment]
Also, when I change my latitude and longitude, run "roslauch fields2cover_ros view_field" and it will say "[visualizer-2] process has died[pid 160817, exit code -11....]". Currently, my settings are: EPSG: 4326 (latitude and longitude)(WGS-84), EPSG: 21463 (meters).




吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
https://epsg.io/?q=china

**Comment by Gonzalo-Mier** [comment]
Not understanding your error. Provide more details please. Also consider that the data in example1 field are related to a position in The Netherlands. Transforming them to EPSG:21463 don't make sense and the field obtained can be not valid

**Comment by 9lovewh** [comment]
I have changed EPSG: 28992 (Netherlands) to EPSG: 1067 (China), changed EPSG: 4258 in example1. xml to EPSG: 4326, and changed longitude and latitude to<gml: coordinates&gt;24.6068361307118.079323875 24.607873933618.079323875 24.60847477708118.07972149 24.606836130711818.079323875</gml: coordinates&gt;. The following error occurred during recompilation and execution:


[visualizer-2] process has died [pid 169834, exit code -11, cmd /home/fields2cover/fields2cover_ws/devel_isolated/fields2cover_ros/lib/fields2cover_ros/visualizer_node __name:=visualizer __log:=/home/fields2cover/.ros/log/209d5b18-d9dd-11ed-ac1c-a7c0962ddd22/visualizer-2.log].
log file: /home/fields2cover/.ros/log/209d5b18-d9dd-11ed-ac1c-a7c0962ddd22/visualizer-2*.log


Looking forward to your reply. Thank you very much.


吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
Not understanding your error. Provide more details please. Also consider that the data in example1 field are related to a position in The Netherlands. Transforming them to EPSG:21463 don't make sense and the field obtained can be not valid

**Comment by 9lovewh** [comment]
When I change EPSG:4258 in example1.xml to EPSG:4326, I don't know what changes EPSG:28992 should make because the Chinese plane coordinates are not found in the EPSG website.




吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
Not understanding your error. Provide more details please. Also consider that the data in example1 field are related to a position in The Netherlands. Transforming them to EPSG:21463 don't make sense and the field obtained can be not valid

**Comment by 9lovewh** [comment]
Thank you for your continued support, I have successfully achieved the replacement of latitude and longitude, the original error was reported because the order of latitude and longitude was wrong, adjust it to display normally, thank you again.




吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
Not understanding your error. Provide more details please. Also consider that the data in example1 field are related to a position in The Netherlands. Transforming them to EPSG:21463 don't make sense and the field obtained can be not valid

**Comment by 9lovewh** [comment]
At present, the only problem with the path is that its waypoint only has position information and no attitude information, such as yaw angle, and the yaw angle information of the waypoint is very important to achieve precise motion control.




吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
Not understanding your error. Provide more details please. Also consider that the data in example1 field are related to a position in The Netherlands. Transforming them to EPSG:21463 don't make sense and the field obtained can be not valid

**Comment by Gonzalo-Mier** [comment]
That information is provided by the Fields2Cover library, but not added into the ROS interface. Maybe you can propose a solution for it :)

**Comment by 9lovewh** [comment]
Thank you very much for your answer, I will try further and will communicate with you immediately if there is any progress. What we're currently working on is also a driverless agricultural machinery project.




吴江东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fields2Cover/fields2cover_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月14日(星期五) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fields2Cover/fields2cover_ros] Cmake error (Issue #16)





 
That information is provided by the Fields2Cover library, but not added into the ROS interface. Maybe you can propose a solution for it :)

**Comment by Gonzalo-Mier** [comment]
I will close this issue then :) Happy to help. 

It woud be awesome if you write me more about your project at https://github.com/Fields2Cover/Fields2Cover/discussions/31 or in a private email. It is always nice to know how and for which purpose people use your effort. Thanks again!!
