### ISSUE TITLE
roslaunch error

### ISSUE THREAD

**Issue by MrDragon2** [Fields2Cover/fields2cover_ros#2]
Hello Author , When I run "roslaunch", the terminal reports the following error:
terminate called after throwing an instance of 'std::invalid_argument'
what(): File not found
What is the reason?

And, when viewing the node information, I found the following error:
Node [/visualizer]
Publications:
/field/border [geometry_msgs/PolygonStamped]
/field/no_headlands [geometry_msgs/PolygonStamped]
/field/swaths [visualization_msgs/Marker]
/gps/fix [sensor_msgs/NavSatFix]
/rosout [rosgraph_msgs/Log]
Subscriptions: None
Services:
/visualizer/get_loggers
/visualizer/set_logger_level
contacting node http://lgg:40927/ ...
ERROR: Communication with node[http://lgg:40927/] failed!

**Comment by Gonzalo-Mier** [comment]
Hi @MrDragon2, welcome to the repo.
The error you receive could be caused because the file {folder of fields2cover_ros}/data/example1.xml cannot be found on your system. You can provide any other XML file in the roslaunch instead of the example provided.
Also, it's weird your roscore try to connect to http://lgg. Do you have any custom configuration related to that?

**Comment by MrDragon2** [comment]
The package I run locally, "roscore", runs successfully, and the communication network configuration should not be wrong

**Comment by MrDragon2** [comment]
> Hi @MrDragon2, welcome to the repo. The error you receive could be caused because the file {folder of fields2cover_ros}/data/example1.xml cannot be found on your system. You can provide any other XML file in the roslaunch instead of the example provided. Also, it's weird your roscore try to connect to http://lgg. Do you have any custom configuration related to that?
The package I run locally, "roscore", runs successfully, and the communication network configuration should not be wrong

**Comment by MrDragon2** [comment]
> Hi @MrDragon2, welcome to the repo. The error you receive could be caused because the file {folder of fields2cover_ros}/data/example1.xml cannot be found on your system. You can provide any other XML file in the roslaunch instead of the example provided. Also, it's weird your roscore try to connect to http://lgg. Do you have any custom configuration related to that?

The package I run locally, "roscore", runs successfully, and the communication network configuration should not be wrong

**Comment by Gonzalo-Mier** [comment]
Both roscore and your communication network configuration are okay. I'm suggesting that the problem could be that ros cannot find the file of the field (example1.xml) on the computer running the roslaunch.

**Comment by MrDragon2** [comment]
> Both roscore and your communication network configuration are okay. I'm suggesting that the problem could be that ros cannot find the file of the field (example1.xml) on the computer running the roslaunch.

How is the file "example 1" referenced and what is its content?

**Comment by MrDragon2** [comment]
> Both roscore and your communication network configuration are okay. I'm suggesting that the problem could be that ros cannot find the file of the field (example1.xml) on the computer running the roslaunch.

**Comment by MrDragon2** [comment]
> Both roscore and your communication network configuration are okay. I'm suggesting that the problem could be that ros cannot find the file of the field (example1.xml) on the computer running the roslaunch.

How is the "example 1" file used in the system and what is its content?

**Comment by MrDragon2** [comment]
> Both roscore and your communication network configuration are okay. I'm suggesting that the problem could be that ros cannot find the file of the field (example1.xml) on the computer running the roslaunch.

At present, I run the example of "view_field. launch". In the three nodes, only the/visualizer node appears "ERROR: Communication with node[ http://lgg:40927/ ] failed! "

**Comment by MrDragon2** [comment]
> Both roscore and your communication network configuration are okay. I'm suggesting that the problem could be that ros cannot find the file of the field (example1.xml) on the computer running the roslaunch.

 The file "gps_map. launch" does not use "example. xml", but it also has the problem of the node "/visualizer" .

**Comment by MrDragon2** [comment]
The error reported by "roslaunch fields2cover_ros view_field.launch" is as follows 
"ERROR 6: GEOS support not enabled.
[visualizer-1] process has died [pid 16733, exit code -11, cmd /home/lgg/catkin_ws/devel/lib/fields2cover_ros/visualizer_node __name:=visualizer `__log:=/home/lgg/.ros/log/295b1a8a-6933-11ed-9ca0-f46b8c847f27/visualizer-1.log].`log file: /home/lgg/.ros/log/295b1a8a-6933-11ed-9ca0-f46b8c847f27/visualizer-1*.log"

**Comment by MrDragon2** [comment]
The error reported by "roslaunch fields2cover_ros view_field.launch" is as follows
"ERROR 6: GEOS support not enabled.
[visualizer-1] process has died [pid 16733, exit code -11, cmd /home/lgg/catkin_ws/devel/lib/fields2cover_ros/visualizer_node __name:=visualizer __log:=/home/lgg/.ros/log/295b1a8a-6933-11ed-9ca0-f46b8c847f27/visualizer-1.log].log file: /home/lgg/.ros/log/295b1a8a-6933-11ed-9ca0-f46b8c847f27/visualizer-1*.log".
Also, "rosparam get /visualizer/field_file" shows "/home/lgg/catkin_ws/src/fields2cover_ros/data/example1.xml ",
 It indicates that "example" has been found. Maybe this problem did not cause the program to crash ?

**Comment by MrDragon2** [comment]
> > Both roscore and your communication network configuration are okay. I'm suggesting that the problem could be that ros cannot find the file of the field (example1.xml) on the computer running the roslaunch.
> 
> At present, I run the example of "view_field. launch". In the three nodes, only the/visualizer node appears "ERROR: Communication with node[ http://lgg:40927/ ] failed! "

The error reported by "roslaunch fields2cover_ros view_field.launch" is as follows
"ERROR 6: GEOS support not enabled.
[visualizer-1] process has died [pid 16733, exit code -11, cmd /home/lgg/catkin_ws/devel/lib/fields2cover_ros/visualizer_node __name:=visualizer __log:=/home/lgg/.ros/log/295b1a8a-6933-11ed-9ca0-f46b8c847f27/visualizer-1.log].log file: /home/lgg/.ros/log/295b1a8a-6933-11ed-9ca0-f46b8c847f27/visualizer-1*.log".
Also, "rosparam get /visualizer/field_file" shows "/home/lgg/catkin_ws/src/fields2cover_ros/data/example1.xml ",
It indicates that "example" has been found. Maybe this problem did not cause the program to crash ?

**Comment by MrDragon2** [comment]
> Both roscore and your communication network configuration are okay. I'm suggesting that the problem could be that ros cannot find the file of the field (example1.xml) on the computer running the roslaunch.

The error reported by "roslaunch fields2cover_ros view_field.launch" is as follows
"ERROR 6: GEOS support not enabled.
[visualizer-1] process has died [pid 16733, exit code -11, cmd /home/lgg/catkin_ws/devel/lib/fields2cover_ros/visualizer_node __name:=visualizer __log:=/home/lgg/.ros/log/295b1a8a-6933-11ed-9ca0-f46b8c847f27/visualizer-1.log].log file: /home/lgg/.ros/log/295b1a8a-6933-11ed-9ca0-f46b8c847f27/visualizer-1*.log."

Also, "rosparam get /visualizer/field_file" shows "/home/lgg/catkin_ws/src/fields2cover_ros/data/example1.xml ",
It indicates that "example" has been found. Maybe this problem did not cause the program to crash ?

**Comment by Gonzalo-Mier** [comment]
Weird. Did you follow [the installation guide of Fields2Cover](https://fields2cover.github.io/source/installation.html#requirements-on-linux)? Maybe GDAL is missing, or the version is not correct. I should improve the installation process on this package I guess.

**Comment by MrDragon2** [comment]
> Weird. Did you follow [the installation guide of Fields2Cover](https://fields2cover.github.io/source/installation.html#requirements-on-linux)? Maybe GDAL is missing, or the version is not correct. I should improve the installation process on this package I guess.

 I have installed gdal and Fields2Cover. In addition, I have added a path to the "CmakeLists" in my space according to the process you gave me. But I do not know whether "fields_ros" actually refers to Fields2Cover, because there is no prompt .

**Comment by Gonzalo-Mier** [comment]
How did you install GDAL? The "Error 6: GEOS support..." is actually an error from GDAL. Also check that the GDAL version is greater than 3.0

**Comment by MrDragon2** [comment]
> How did you install GDAL? The "Error 6: GEOS support..." is actually an error from GDAL. Also check that the GDAL version is greater than 3.0

I installed "GDAL-3.3.1". If the GDAL installation fails or the version is less than 3.0, the "Field2Cover" package will have compilation errors, but both my GDAL and Field2Cover have been successfully compiled.

**Comment by MrDragon2** [comment]
The GDAL library installation is very complicated. It took me half a month to complete the compilation.

**Comment by Gonzalo-Mier** [comment]
It seems like you installed GDAL without GEOS support ([https://github.com/r-spatial/sf/issues/1207](https://github.com/r-spatial/sf/issues/1207) ). Just for curiosity, did you also run the tests on Fields2Cover? (`make check` after compilation on the build folder)

**Comment by MrDragon2** [comment]
> It seems like you installed GDAL without GEOS support ([r-spatial/sf#1207](https://github.com/r-spatial/sf/issues/1207) ). Just for curiosity, did you also run the tests on Fields2Cover? (`make check` after compilation on the build folder)

The GDAL library I installed depends on "proj" and "sqlite". It seems that there is no "GEOS" you mentioned.

**Comment by MrDragon2** [comment]
> > It seems like you installed GDAL without GEOS support ([r-spatial/sf#1207](https://github.com/r-spatial/sf/issues/1207) ). Just for curiosity, did you also run the tests on Fields2Cover? (`make check` after compilation on the build folder)
> 
> The GDAL library I installed depends on "proj" and "sqlite". It seems that there is no "GEOS" you mentioned.

In addition, I did not see any content related to "GEOS" in the installation tutorial you provided.

**Comment by Gonzalo-Mier** [comment]
The instructions I provide use `libgdal-dev` which have GEOS installed by default. I do not provide instructions about how to install GDAL by source because it's a complex installation I haven't done myself. As the error on this issue is related with a custom GDAL installation that gets out of the scope of the tutorials, I close this issue. Feel free to make a PR with an improved installation method and the issues you found.
Best regards,
Gonzalo
